name: circularmapper_generator
description: CircularMapper Generator Module
keywords:
  - index
  - genome
  - fasta
  - reference

tools:
  - circularmapper:
      description:  A method to improve mappings on circular genomes, using the BWA mapper.
      homepage: https://github.com/apeltzer/Circularmapper
      documentation: https://circularmapper.readthedocs.io/en/latest/
      doi: "10.1186/s13059-016-0918-z"
      licence: ['GPL v3']

input:
  - fasta:
      type: file
      description: Input genome fasta file
      pattern: "*.{fasta}"

output:
  - index:
      type: file
      description: BWA genome index files
      pattern: "*.{amb,ann,bwt,pac,sa}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@apeltzer"
